name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip #--timeout 60
          pip install pytest tqdm PyYAML #--timeout 60

      - name: Install additional setup dependencies
        run: |
          pip install ruamel.yaml psutil requests #--timeout 60

      - name: Install system dependencies for OpenCV (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-0 \
            libgomp1 \
            libgl1-mesa-dri \
            libglu1-mesa \
            libsm6 \
            libxext6 \
            libxrender-dev \
            libfontconfig1 \
            libice6

      - name: Validate CI setup (fast syntax check)
        run: python tests/test_ci_setup.py

      - name: Build full multi-environment setup (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python setup/setup.py --multi-env --ci-test
        timeout-minutes: 50

      - name: Validate multi-environment imports (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Checking environment structure..."
          find . -name "*env*" -type d | head -20
          echo "Running CI-compatible multi-environment import tests..."
          python tests/test_multi_env_imports_ci.py || (echo "Multi-env test failed, showing environment details..." && ls -la environments/ 2>/dev/null || echo "No environments/ directory found" && exit 1)
