name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest tqdm PyYAML

      - name: Install additional setup dependencies
        run: |
          pip install ruamel.yaml psutil requests

      - name: Validate CI setup
        run: python tests/test_ci_setup.py

      - name: Run setup script (single or multi)
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            python setup/setup.py --multi-env --dry-run || true  # Use dry-run to avoid heavy installs in CI
          else
            python setup/setup.py --dry-run || true
          fi

      - name: Run tests
        run: pytest -q 