name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (base venv)
        run: |
          python -m pip install --upgrade pip
          pip install pytest tqdm

      - name: Run setup script (single or multi)
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            python setup/setup.py --multi-env || true  # heavy, ignore failures for smoke CI
          else
            python setup/setup.py --dry-run || true
          fi

      - name: Run tests
        run: pytest -q 