name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip --timeout 60
          pip install pytest tqdm PyYAML

      - name: Install additional setup dependencies
        run: |
          pip install ruamel.yaml psutil requests --timeout 60

      - name: Validate CI setup (fast syntax check)
        run: python tests/test_ci_setup.py

      - name: Test multi-environment setup (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python setup/setup.py --multi-env --ci-test
        timeout-minutes: 20

      - name: Validate multi-environment imports (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          if [ -d "detection_env" ] && [ -d "ocr_env" ]; then
            echo "Multi-environments found, running import tests..."
            python tests/test_multi_env_imports.py
          else
            echo "Multi-environments not found (CI test mode), skipping import tests"
            echo "V Multi-environment import tests skipped in CI mode"
          fi 